server:
  port: 8085

  servlet:
    application-display-name: monitor-server
    context-path: /monitor/
spring:
  application:
    name: monitor-server
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/